### ISSUE TITLE
To-do for Crisis

### ISSUE THREAD

**Issue by SebastianTanoni** [AzerothWarsLR/WarcraftLegacies#1711]
- [x] Config for all the factions
- [x] finish their tech tree
- [x] finish the picking system
- [x] add the building and research to pick the faction and the team (captain)
- [x] finish the spawn triggers for all the other crisis
- [x] make sure that you cant abuse and make the picking seperated
- [x] setup all the legend files
- [x] make the condition to unlock the factions quest
