### ISSUE TITLE
The grand tooltip review

### ISSUE THREAD

**Issue by YakaryBovine** [AzerothWarsLR/WarcraftLegacies#817]
We have decided to perform a review of all player-visible tooltips in the game. This work will take place over multiple versions, and will be distributed by faction. HerrDave and Lordsebas will each take half of the factions in the game, while YakaryBovine will perform a final review of all factions.

Reviewers are responsible for identifying **and** fixing the problems that they see.

Below is a list of all factions that still need to be done. 

- [x] [Frostwolf](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1065)
- [x] [Lordaeron](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1058)
- [x] [Quel'thalas](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1068)
- [x] [Scourge](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1069)
- [x] [Ironforge](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1075)
- [x] [Warsong](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1070)
- [x] [Fel Horde](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1071)
- [x] [Dalaran](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1072)
- [x] [Goblin](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/816)
- [x] [Stormwind](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1073)
- [x] [Druids](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1066)
- [x] [Draenei](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/853)
- [x] [Illidan](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/936)
- [x] [Sentinels](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1064)
- [x] [Kul'tiras](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/810)
- [x] [Legion](https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1062)

**Tooltip quality checklist**
* All units, abilities, researches, and upgrades are formatted to the standard
* All unit and hero extended tooltips mention every ability they know and every ability they can learn
* All structure extended tooltips mention all abilities they have, units they can upgrade to, units they can train, and researches they can research
* All train, build, upgrade and research tooltips match the name of the object
* All caster upgrade tooltips list all abilities the caster has learned
* All icons match the icon formatting rules (found on Discord)
* All unit limit tooltips are accurate

**Comment by HerrDave** [comment]
Ironforge done
Sleep schedule too @u@

**Comment by YakaryBovine** [comment]
Lordaeron review: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/1058
